name: generate-builds
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-otrgui:
    runs-on: ${{ (vars.WINDOWS_RUNNER && fromJSON(vars.WINDOWS_RUNNER)) || 'windows-latest' }}
    steps:
    - name: Install dependencies
      if: ${{ !vars.WINDOWS_RUNNER }}
      run: |
        choco install ninja
        Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: dcvz/ccache-action@27b9f33213c0079872f064f6b6ba0233dfa16ba2
      with:
        key: ${{ runner.os }}-ccache
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build OTRGui
      run: |
        set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build-windows --target OTRGui --config Release --parallel 10
        mkdir otrgui
        mv ./x64/Release/OTRGui.exe ./otrgui/OTRGui.exe
        mv ./build-windows/OTRGui/assets ./otrgui
        mv ./build-windows/ZAPD/ZAPD.exe ./otrgui/assets/extractor/ZAPD.exe
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: OTRGui
        path: otrgui
